### ISSUE TITLE
Unable to find build step in VSTS

### ISSUE THREAD

**Issue by tastyeggs** [isaacabraham/vsts-fsharp#1]
I added "F# Helpers for VSTS " on my VSTS site (hosted on visualstudio.com), but I'm unable to find any new build steps - Paket or FAKE. Is there a step I'm missing?

**Comment by isaacabraham** [comment]
Hmmm. As long as you've gone through the install process and got the "success" dialog - you should then be able to go into Build and see them. They're in the Build and Package sections.

**Comment by tastyeggs** [comment]
Strange, I did, see [screenshots here](http://imgur.com/a/byFlv)

Does this work with VSTS or only TFS?

**Comment by tastyeggs** [comment]
Ok, should have tried this before. Uninstalling and reinstalling works. Strange.

Thanks :)

**Comment by isaacabraham** [comment]
Nice - oh well!
