### ISSUE TITLE
Update GitHub repository and add link to marketplace

### ISSUE THREAD

**Issue by matthid** [isaacabraham/vsts-fsharp#20]
![image](https://user-images.githubusercontent.com/1866463/45327689-d7f97700-b558-11e8-8e56-c0ba62baeede.png)

@isaacabraham Can you update the text and add a link to the marketplace page https://marketplace.visualstudio.com/items?itemName=isaacabraham.fsharp-helpers-extension ?

**Comment by isaacabraham** [comment]
Done. Should I remove the repo as well e.g. azure-devops-fsharp?

**Comment by matthid** [comment]
![image](https://user-images.githubusercontent.com/1866463/45346071-6f39eb00-b5a8-11e8-9598-632362909883.png)

Lets see what Microsoft is doing

**Comment by matthid** [comment]
Thanks!
