### ISSUE TITLE
Run F# script does not support F# 4.5

### ISSUE THREAD

**Issue by san-86** [isaacabraham/vsts-fsharp#29]
### Description

Hi Isaac, thank you for these great tools, I have a F# library that is build with F# 4.5 , this is not complient with your Run F# script, I'm running it on a VS2017 Hosted Agent, 

I have tried setting the FSharp version Parameter to 4.5 but that give me a Path not found error.

### Repro steps
1. Run a script that is build with F# 4.5 via the run F# script and set FSharpVersion parameter to 4.5

### Expected behavior

I expect the Script to Run and the fsi.exe path to support F# 4.5

### Actual behavior

the path is made to be somthing like : C:\Program Files (x86)\Microsoft SDKs\F#\4.5\Framework\v4.0\fsi.exe"

This path does not exist.

### Known workarounds

I can make a simple CMD line task and then hardcode the path to a place on the Agent where F#4.5 is supported

**Comment by isaacabraham** [comment]
Mmmm. We probably should make the task configurable so that you can supply either the path to FSI or the version - the path seems to keeps changing every time there's a new FSI which is a pain. @matthid any thoughts on the best way to do this?

**Comment by henrikhannemose** [comment]
We are successfully using #30 as a fix for this issue. What are your thoughts on merging that PR, @isaacabraham?

**Comment by isaacabraham** [comment]
Ooops. Sorry. No complaints. let me merge and then release tomorrow. @matthid anything I need to know about with the release process changes since all the recent work you've done?

**Comment by henrikhannemose** [comment]
Thanks for merging the PR, Isaac!

Do you know what it takes to get the [nuget package](https://marketplace.visualstudio.com/items?itemName=isaacabraham.fsharp-helpers-extension) updated to be the most recent version? Right now I see _Last updated | 9/13/2018_

**Comment by isaacabraham** [comment]
Yes, I can push it - I just need to check with Mattias that nothing has changed recently. Sorry for the delay.

**Comment by isaacabraham** [comment]
@henrikhannemose just a heads up - i'm trying to deploy but there's an issue with the new script so i need to figure it out. please bear with me.

**Comment by henrikhannemose** [comment]
No problem. Thanks for the heads up. I appreciate your effort! :)

**Comment by isaacabraham** [comment]
@henrikhannemose right - can you check to see if the new version has your changes in it? Apologies again for the long time it's taken to push this through - hopefully this is now done, finally.

**Comment by henrikhannemose** [comment]
Thanks, @isaacabraham! It works just as expected 👍
