### ISSUE TITLE
Release of the new Tasks is broken

### ISSUE THREAD

**Issue by matthid** [isaacabraham/vsts-fsharp#8]
See report in https://github.com/matthid/Paket.TeamBuildCredentials/issues/1

**Comment by isaacabraham** [comment]
@matthid @sdargaud yes, looks like an error with the packaging - sorry about that. We'll try to fix this ASAP but there's an with FAKE that first needs fixing in order to get this to work... sorry.

**Comment by isaacabraham** [comment]
@sdargaud can you try again with 1.1.3?

**Comment by sdargaud** [comment]
It's working, no more error message with 1.1.3, thanks!

**Comment by mgaspar** [comment]
Hi @isaacabraham - thanks for this quick fix! 
The only note I would add is that the task version was not updated (it's still 0.1.1), and I had to manually delete the task folder in the build agent so that it would pick up the new version. It's probably not an issue for those using Hosted agents.

**Comment by isaacabraham** [comment]
Doh. I'll update it for the next release - I suspect that only a few people got the original "bad" release so it should be ok going forwards.
